# From https://blog.michaelkelly.org/2023/05/mirroring-sourcehut-repositories-to-github/

image: alpine/edge
secrets:
  - "b9447561-6f6d-426d-8e55-1d2dc0790257"
environment:
  REPO: "min-terminal"
  GH_USER: "emmabastas"
tasks:
  - write-ssh-config: |
      cat <<_FILE_ >> ~/.ssh/config
      Host github.com
        IdentityFile ~/.ssh/id_rsa
        IdentitiesOnly yes
        BatchMode yes
        StrictHostKeyChecking no
      _FILE_
  - add-mirror-disclaimer: |
      cd ~/"${REPO}"
      mv README.md README-original.md
      cat <<_FILE_ > ./README.md
      > ⚠️ This repository is a mirror of https://sr.ht/~emmabastas/min-terminal/
      > If you want to open issues here on GitHub that's completely fine, but
      > if you want to make a fork it's best to use the SourceHut repository instead.

      _FILE_
      cat README-original.md >> README.md
      rm README-original.md

      git checkout -b mirroring-disclaimer
      git add ./README.md
      git commit -m "Add mirroring disclaimer"
  - push-to-github: |
      cd ~/"${REPO}"
      # remove remotes/origin/HEAD so we don't push it
      git remote set-head origin -d
      git remote add github "git@github.com:${GH_USER}/${REPO}.git"
      git push --prune --force github mirroring-disclaimer:main
