#include "termbuf.h"

#include <stdbool.h>
#include <assert.h>
#include <X11/Xlib.h>
#include <X11/Xft/Xft.h>

#include "CuTest.h"

// Shoutout https://poor.dev/blog/terminal-anatomy/



void termbuf_initialize(int nrows, int ncols, struct termbuf *tb_ret) {
    assert(nrows > 0);
    assert(ncols > 0);

    tb_ret->nrows = nrows;
    tb_ret->ncols = ncols;
    tb_ret->row = nrows;
    tb_ret->col = 1;
    tb_ret->flags = FLAG_LENGTH_0;
    tb_ret->fg_color_r = 255;
    tb_ret->fg_color_g = 255;
    tb_ret->fg_color_b = 255;
    tb_ret->bg_color_r = 10;
    tb_ret->bg_color_g = 10;
    tb_ret->bg_color_b = 10;

    tb_ret->p_state = P_STATE_GROUND;

    tb_ret->buf = calloc(nrows * ncols, sizeof(struct termbuf_char));
    if (tb_ret->buf == NULL) {
        assert(false);
    }
}

void termbuf_insert(struct termbuf *tb, uint8_t *utf8_char, int len) {
    assert(len > 0);
    assert(len <= 4);

    size_t index = (tb->row - 1) * tb->ncols + (tb -> col - 1);
    memcpy(tb->buf[index].utf8_char, utf8_char, 4);
    tb->flags = (tb->flags & ~FLAG_LENGTH_MASK) | len;
    // TODO pref: use memcpy instead.
    tb->buf[index].flags = tb->flags;
    tb->buf[index].fg_color_r = tb->fg_color_r;
    tb->buf[index].fg_color_g = tb->fg_color_g;
    tb->buf[index].fg_color_b = tb->fg_color_b;
    tb->buf[index].bg_color_r = tb->bg_color_r;
    tb->buf[index].bg_color_g = tb->bg_color_g;
    tb->buf[index].bg_color_b = tb->bg_color_b;

    tb->col ++;

    if (tb->col > tb->ncols) {
        tb->col = 1;
        tb->row ++;
        if (tb->row > tb->nrows) {
            //assert(false);
            tb->row = 1;
        }
    }
}

void termbuf_render(struct termbuf *tb,
                    Display *display,
                    int window,
                    int screen,
                    XftDraw *draw,
                    XftFont *font,
                    int cell_width,
                    int cell_height) {
    assert(cell_width > 0);
    assert(cell_height > 0);

    XRenderColor fg;
    XftColor color_foreground;
    GC gc = XCreateGC(display,
                      window,
                      0,
                      NULL);

    for (int row = 1; row <= tb->nrows; row ++) {
        for (int col = 1; col <= tb->ncols; col ++) {
            struct termbuf_char *c =
                tb->buf + (row - 1) * tb->ncols + col - 1;

            XSetForeground(display, gc,
                           (c->bg_color_r << 16)
                           + (c->bg_color_g << 8)
                           + c->bg_color_b);

            XFillRectangle(
                display,
                window,
                gc,
                (col - 1) * cell_width,
                (row - 1) * cell_height,
                cell_width,
                cell_height);

            if (c->flags & FLAG_LENGTH_MASK == FLAG_LENGTH_0) {
                continue;
            }

            fg = (XRenderColor) { c->fg_color_r << 8,
                                  c->fg_color_g << 8,
                                  c->fg_color_b << 8,
                                  65535 };

            XftColorAllocValue(
                display,
                DefaultVisual(display, screen),
                DefaultColormap(display, screen), &fg,
                &color_foreground);

            XftDrawStringUtf8(
              draw,
              &color_foreground,
              font,
              (col - 1) * cell_width,
              (row - 1) * cell_height + cell_height,
              (XftChar8 *) c,
              c->flags & FLAG_LENGTH_MASK);
        }
    }
}



/*
 * Parsing logic
 */



struct parser_table_entry {
    enum parser_state new_state;
    void (*action)(struct termbuf *tb, char ch);
};

struct parser_table_entry parser_table[256 * NSTATES];

void termbuf_parse(struct termbuf *tb, uint8_t *data, size_t len) {
    while (len > 0) {
        size_t index = tb->p_state * 256 + *data;
        struct parser_table_entry entry = parser_table[index];

        tb->p_state = entry.new_state;
        entry.action(tb, *data);

        data ++;
        len --;
    }
}

void action_print(struct termbuf *tb, char ch) {
    termbuf_insert(tb, (uint8_t *) &ch, 1);
}

void action_utf8_chomp_start(struct termbuf *tb, char ch) {
    tb->p_data.utf8_chomping = (struct utf8_chomping) {
        .len = 1,
        .utf8_char = { ch, 0, 0, 0 },
    };
}

void action_utf8_chomp_continue(struct termbuf *tb, char ch) {
    struct utf8_chomping *data = &tb->p_data.utf8_chomping;

    assert(data->len <= 2);

    data->utf8_char[data->len] = ch;
    data->len ++;
}

void action_utf8_chomp_end(struct termbuf *tb, char ch) {
    struct utf8_chomping *data = &tb->p_data.utf8_chomping;

    assert(data->len <= 3);

    data->utf8_char[data->len] = ch;
    data->len ++;

    termbuf_insert(tb, (uint8_t *) &data->utf8_char, data->len);
}

void action_fail(struct termbuf *tb, char ch) {
    assert(false);
}

/*[[[cog
import cog

def r(start, end):
    return range(start, end + 1)

P_STATE_GROUND = "P_STATE_GROUND"
P_STATE_CHOMP1 = "P_STATE_CHOMP1"
P_STATE_CHOMP2 = "P_STATE_CHOMP2"
P_STATE_CHOMP3 = "P_STATE_CHOMP3"

action_fail                = "action_fail"
action_print               = "action_print"
action_utf8_chomp_start    = "action_utf8_chomp_start"
action_utf8_chomp_continue = "action_utf8_chomp_continue"
action_utf8_chomp_end      = "action_utf8_chomp_end"

table = [
  ##################
  # P_STATE_GROUND #
  ##################
  # Got an ASCII character / single-byte utf8.
  [ P_STATE_GROUND, r(0  , 127), P_STATE_GROUND, action_print                 ],
  # Got a utf8 contiuation byte when not expecting it.
  [ P_STATE_GROUND, r(128, 191), P_STATE_GROUND, action_fail                  ],
  # Got an "unused" byte.
  [ P_STATE_GROUND, r(192, 193), P_STATE_GROUND, action_fail                  ],
  # Got the start of a 2-byte utf-8.
  [ P_STATE_GROUND, r(194, 223), P_STATE_CHOMP1, action_utf8_chomp_start      ],
  # Got the start of a 3-byte utf-8.
  [ P_STATE_GROUND, r(224, 239), P_STATE_CHOMP2, action_utf8_chomp_start      ],
  # Got the start of a 4-byte utf-8.
  [ P_STATE_GROUND, r(240, 244), P_STATE_CHOMP3, action_utf8_chomp_start      ],
  # Go an "unused" byte.
  [ P_STATE_GROUND, r(245, 255), P_STATE_GROUND, action_fail                  ],

  ##################
  # P_STATE_CHOMP1 #
  ##################
  # Got an unexpected ASCII character / single-byte utf8.
  [ P_STATE_GROUND, r(0  , 127), P_STATE_GROUND, action_fail                  ],
  # Got the final utf8 contiuation byte.
  [ P_STATE_GROUND, r(128, 191), P_STATE_GROUND, action_utf8_chomp_end        ],
  # Got an "unused" byte.
  [ P_STATE_GROUND, r(192, 193), P_STATE_GROUND, action_fail                  ],
  # Got an unexpected start of a 2-byte utf-8.
  [ P_STATE_GROUND, r(194, 223), P_STATE_CHOMP1, action_fail                  ],
  # Got an unexpected start of a 3-byte utf-8.
  [ P_STATE_GROUND, r(224, 239), P_STATE_CHOMP2, action_fail                  ],
  # Got an unexpected start of a 4-byte utf-8.
  [ P_STATE_GROUND, r(240, 244), P_STATE_CHOMP3, action_fail                  ],
  # Go an "unused" byte.
  [ P_STATE_GROUND, range(245, 255), P_STATE_GROUND, action_fail    ],

  ##################
  # P_STATE_CHOMP2 #
  ##################
  # Got an unexpected ASCII character / single-byte utf8.
  [ P_STATE_GROUND, r(0  , 127), P_STATE_GROUND, action_fail                  ],
  # Got a utf8 contiuation byte.
  [ P_STATE_GROUND, r(128, 191), P_STATE_CHOMP1, action_utf8_chomp_continue   ],
  # Got an "unused" byte.
  [ P_STATE_GROUND, r(192, 193), P_STATE_GROUND, action_fail                  ],
  # Got an unexpected start of a 2-byte utf-8.
  [ P_STATE_GROUND, r(194, 223), P_STATE_CHOMP1, action_fail                  ],
  # Got an unexpected start of a 3-byte utf-8.
  [ P_STATE_GROUND, r(224, 239), P_STATE_CHOMP2, action_fail                  ],
  # Got an unexpected start of a 4-byte utf-8.
  [ P_STATE_GROUND, r(240, 244), P_STATE_CHOMP3, action_fail                  ],
  # Go an "unused" byte.
  [ P_STATE_GROUND, r(245, 255), P_STATE_GROUND, action_fail                  ],

  ##################
  # P_STATE_CHOMP3 #
  ##################
  # Got an unexpected ASCII character / single-byte utf8.
  [ P_STATE_GROUND, r(0  , 127), P_STATE_GROUND, action_fail                  ],
  # Got a utf8 contiuation byte.
  [ P_STATE_GROUND, r(128, 191), P_STATE_CHOMP2, action_utf8_chomp_continue   ],
  # Got an "unused" byte.
  [ P_STATE_GROUND, r(192, 193), P_STATE_GROUND, action_fail                  ],
  # Got an unexpected start of a 2-byte utf-8.
  [ P_STATE_GROUND, r(194, 223), P_STATE_CHOMP1, action_fail                  ],
  # Got an unexpected start of a 3-byte utf-8.
  [ P_STATE_GROUND, r(224, 239), P_STATE_CHOMP2, action_fail                  ],
  # Got an unexpected start of a 4-byte utf-8.
  [ P_STATE_GROUND, r(240, 244), P_STATE_CHOMP3, action_fail                  ],
  # Go an "unused" byte.
  [ P_STATE_GROUND, r(245, 255), P_STATE_GROUND, action_fail                  ],
]

cog.outl("struct parser_table_entry parser_table[256 * NSTATES] = {")
for [state, events, newstate, action] in table:
    for event in events:
        cog.outl("    { .new_state = %s," % newstate)
        cog.outl("      .action = &%s, }," % action)
cog.outl("};")

cog.outl("// Hello :-)")
]]]*/
struct parser_table_entry parser_table[256 * NSTATES] = {
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_print, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_utf8_chomp_start, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_utf8_chomp_end, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_utf8_chomp_continue, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP1,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP2,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_CHOMP3,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
    { .new_state = P_STATE_GROUND,
      .action = &action_fail, },
};
// Hello :-)
//[[[end]]]



/*
 * Unit tests bellow
 */

CuSuite *termbuf_test_suite() {
    CuSuite *suite = CuSuiteNew();
    return suite;
}
